# Introduction To Data Science

This is our first session for numpy.

In [2]:
import numpy as np    

In [3]:
l = [20,50,30,60,70,10,100] 

list  ----------->           array  

slow                        fast 
heterogeneous              homogeneous
[1,2,3,'pooja',4.5]        [1.2,2.3]
element wise XXX           element wise 
mathematical XXX           mathematical 

# Array Conversion

In [4]:
arr = np.array(l)  
print(arr)

[ 20  50  30  60  70  10 100]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
l = [20,50,30,60,70,10,100.45]

arr = np.array(l)  
print(arr)

[ 20.    50.    30.    60.    70.    10.   100.45]


In [7]:
l = [20,50,30,60,70,10,100.45]

arr = np.array(l,dtype=int)  
print(arr)

[ 20  50  30  60  70  10 100]


# Element Wise Operation

In [8]:
l = [20,50,30,60,70,10,100.45]
arr = np.array(l)   
print(arr + 5)

[ 25.    55.    35.    65.    75.    15.   105.45]


In [9]:

l = [24,56,78,99]

arr  = np.array(l)

print(arr / 2)


[12.  28.  39.  49.5]


In [10]:
price = [20,40,10,30]
quantity = [10,20,5,9]

price = np.array(price)
quantity = np.array(quantity)

print(price * quantity)

[200 800  50 270]


In [11]:
print(price*20/100)

[4. 8. 2. 6.]


In [12]:
l = [20,50,30,60,70,10,100.45]
arr = np.array(l) 
print(arr)

[ 20.    50.    30.    60.    70.    10.   100.45]


# sum

In [13]:
total_sale = np.sum(arr)
total_sale

340.45

# max

In [14]:
highest_sale = np.max(arr)
highest_sale

100.45

# min

In [15]:
lowest_sale = np.min(arr)   
lowest_sale

10.0

# average

In [21]:
np.mean(arr)

48.635714285714286

# round

In [32]:
l = [48.5,76.8,32.45,98.76]
arr = np.array(l)   
print(arr)

[48.5  76.8  32.45 98.76]


In [33]:
arr = np.round(arr)
print(arr)

[48. 77. 32. 99.]


# arange

In [36]:
arr = np.arange(1,100,2)  
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


# random

In [37]:
arr = np.random.randint(50,100,5)
print(arr)

[73 51 77 73 88]


In [38]:
arr = np.random.uniform(50,100,5)
print(arr)

[68.58545509 64.69175093 95.72795109 58.56720156 50.96370413]


In [39]:
arr = np.round(arr,2)
print(arr)

[68.59 64.69 95.73 58.57 50.96]


# cumsum - cumulative sum 

In [41]:
l = [73,51,77,73,88]
arr = np.array(l)  
x = np.cumsum(arr)   
print(x)


[ 73 124 201 274 362]


# Multidimensional list 

In [44]:
virat = [20,40,100,40,50]
dhoni = [100,98,20,21,44]
sachin = [76,88,100,90,76]

l = [ virat,dhoni,sachin ]

print(l)

[[20, 40, 100, 40, 50], [100, 98, 20, 21, 44], [76, 88, 100, 90, 76]]


        0    1   2   3   4     
0    [[20, 40, 100, 40, 50], 
1    [100, 98, 20, 21, 44], 
2    [76, 88, 100, 90, 76]]

      

In [51]:
arr = np.array(l)   
print(arr)

[[ 20  40 100  40  50]
 [100  98  20  21  44]
 [ 76  88 100  90  76]]


In [52]:
total_score = np.sum(arr)
print(total_score)

963


250

In [54]:
match_score = np.sum(arr,axis=0)  
print(match_score)

[196 226 220 151 170]


In [57]:
player_score = np.sum(arr,axis=1)   
print(player_score)


[250 283 430]


250