# Introduction To Data Science

This is our first session for numpy.

In [8]:
import numpy as np    

In [11]:
l = [20,50,30,60,70,10,100] 

list  ----------->           array  

slow                        fast 
heterogeneous              homogeneous
[1,2,3,'pooja',4.5]        [1.2,2.3]
element wise XXX           element wise 
mathematical XXX           mathematical 

# Array Conversion

In [12]:
arr = np.array(l)  
print(arr)

[ 20  50  30  60  70  10 100]


In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
l = [20,50,30,60,70,10,100.45]

arr = np.array(l)  
print(arr)

[ 20.    50.    30.    60.    70.    10.   100.45]


In [18]:
l = [20,50,30,60,70,10,100.45]

arr = np.array(l,dtype=int)  
print(arr)

[ 20  50  30  60  70  10 100]


# Element Wise Operation

In [24]:
l = [20,50,30,60,70,10,100.45]
arr = np.array(l)   
print(arr + 5)

[ 25.    55.    35.    65.    75.    15.   105.45]


In [28]:

l = [24,56,78,99]

arr  = np.array(l)

print(arr / 2)


[12.  28.  39.  49.5]


In [31]:
price = [20,40,10,30]
quantity = [10,20,5,9]

price = np.array(price)
quantity = np.array(quantity)

print(price * quantity)

[200 800  50 270]
